name: Execute Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - run: mvn -v
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Download Maven dependencies
        run: mvn clean dependency:resolve

      - name: Build and run Tests with Maven
        run: mvn clean verify
